In [1]:
import numpy as np

In [2]:
# criando uma matriz e verificando
x = np.array([1, 2, 3, 4]) 
print(x[0])

1


In [3]:
# Fill in the blanks to define a valid numpy array and output its 3rd element:

a = np.array([42, 33, 11, 8, 1])

print(a[2])

11


In [4]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
 
print(x[2][2])

9


In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
print(x.ndim) # 2
print(x.size) # 9
print(x.shape) # (3, 3)

In [38]:
# adicionando elemento

z = np.array([2, 1, 3])

z = np.append(z, [1, 2, 3])
print(z)

[2 1 3 1 2 3]


In [39]:
# deletando elemnto
z = np.delete(z, [0, 3])
print(z)

[1 3 2 3]


In [40]:
# ordenar elementos
z = np.sort(z)
print(z)

[1 2 3 3]


In [44]:
# gerando uma matriz
z1 = np.arange(2, 14, 2)
print(z1)

[ 2  4  6  8 10 12]


In [45]:
x = np.arange(2, 8, 2)
#x = np.append(x, x.size)

# x = np.sort(x)
# print(x[1])
x

3
